apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-backend
  namespace: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-backend
  template:
    metadata:
      labels:
        app: sms-backend
    spec:
      containers:
      - name: backend
        image: sarangasl/sms-backend:latest 
        ports:
        - containerPort: 3001
      
      # 1. මුලින්ම මුළු .env එකම එක පාර load කරනවා
      envFrom:
        - secretRef:
            name: sms-backend-env

      env:
        - name: NODE_ENV
          value: "production" # Cluster එකේ දුවද්දී production දාන එක හොඳයි
---
apiVersion: v1
kind: Service
metadata:
  name: sms-backend-service
  namespace: student-app
spec:
  selector:
    app: sms-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001