apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-frontend
  namespace: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-frontend
  template:
    metadata:
      labels:
        app: sms-frontend
    spec:
      containers:
      - name: frontend
        image: sarangasl/sms-client:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sms-frontend-service
  namespace: student-app
spec:
  selector:
    app: sms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort 