apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-management-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sarangas001/student-management-ops' 
    targetRevision: HEAD
    path: k8s 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true