apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  namespace: student-mgmt
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<username>:<password>@cluster.mongodb.net/dbname"
  JWT_SECRET: "your_jwt_secret_here"
  GEMINI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta/openai/"
  GEMINI_API_KEY: "your_gemini_api_key_here"
  GEMINI_MODEL: "gemini-2.5-flash"